### ISSUE TITLE
Slot manager shows the wrong card type

### ISSUE THREAD

**Issue by Genbox** [GameTec-live/ChameleonUltraGUI#167]
I have read a card and saved it as can be seen under saved cards:

![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/657616/8ae97099-d5a8-4406-8a73-afe63aadcb9b)

However, if I select the Mifare Classic 1K EV1 card (slot 2 in the picture) it shows up as Mifare Classic 2K:

![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/657616/91b08afa-66fb-4a9a-a552-c5a20ad8090b)

Should it not say `Mifare Classic 1K EV1` like on the Saved Cards page?

**Comment by GameTec-live** [comment]
it shows as MFC2k, because a EV1 contains data on sectors a normal mfc1k doesnt have (16 and 17), but the chameleon only supports 1k, 2k and 4k, so we set the slot to 2k which makes 16 and 17 accesible and then load the card into there. Everything is fine and works as intended, the Slotmanager just shows you a different form of the truth ;p

**Comment by Genbox** [comment]
That makes sense. Thanks for the ultra-quick response!
