### ISSUE TITLE
App triggers from device buttons

### ISSUE THREAD

**Issue by tkerby** [GameTec-live/ChameleonUltraGUI#345]
Would be incredible to be able to select a slot then long press to trigger an action in the app such as reading, running a nested attack and writing back to the slot. Would allow for covert operations. 

May need to set the app to stay open in some way to monitor button presses

**Comment by GameTec-live** [comment]
> Would be incredible to be able to select a slot then long press to trigger an action in the app such as reading, running a nested attack and writing back to the slot. Would allow for covert operations. 
> 
> May need to set the app to stay open in some way to monitor button presses

the app staying open wouldnt be the problem, just dont let your phone sleep... the bigger problem would be, that wed somehow need to monitor the buttons, etc. Thatd need to be a fw thing and idk how useful thatd be, as the cli wouldnt have much of a use out of it and you need to have a running client connected...
Wed also prpbably need a "priority" system, so that the button action happens in a timly manner...

**Comment by Foxushka** [comment]
No, why? If you need to open app, you could afford clicking 2 more buttons to read card :roll_eyes:

**Comment by GameTec-live** [comment]
why not, its a interesting concept... And as said, that allow for more covert operation, just having your phone tucked away and being able to run a full clone for example would be useful for some... its very low priority, but why not...

**Comment by Foxushka** [comment]
Then move issue into firmware repo, we can't (and won't) do anything with that. This requires huge protocol modification

**Comment by Foxushka** [comment]
As I said, not possible without firmware. Create issue in firmware.

**Comment by GameTec-live** [comment]
ok, then @tkerby please open a issue for the firmware side (sending button presses to the client) and this will be reponened when thats implemented 🤷
