### ISSUE TITLE
"Use UID/SAK/ATQA from 0 block" should be default behavior?

### ISSUE THREAD

**Issue by telephasicworkshop** [GameTec-live/ChameleonUltraGUI#389]
In the Card Slot Data, while it's handy to have this simple summary of UID and this other data, I find it's confusing and maybe sometimes problematic to allow UID/SAK/ATQA data to differ between the UI slot data and the actual block 0 data.

Is it a good idea to make it standard behavior to update block 0 data if it is changed in the Card Slot, and vice versa?

Ideal would be to also check and/or generate the checksum to avoid issues.

**Comment by GameTec-live** [comment]
Altough this might sound like a good idea at first, it isnt... Why? Because when you dump a card the data from block 0 can actually be different than its reported data.
This setting exists for some edgecases, but the default behaviour works as intended.

Checksum who what where? If you mean after loading the data to a slot, that too might sound good at first but isnt so good afterall. Because to do a checksum you need all of the data, on the Chameleon. Resulting in double the already slow upload time.

**Comment by telephasicworkshop** [comment]
whoa hey ho i wasnt suggesting to _remove_ the possibility to have different data, just to make it match by default if that is the more likely case. if there are other cases, edge cases as you say, then i thought why not let the minority of users who need that be the ones who change the setting? not a big deal.

i had imagined that updating of the slot worked in 2 directions, but now i see that changing the slot data (UID, etc) doesn't actually change the block 0 data. maybe that'd be a nice-to-have.

checksum: i actually meant to say BCC. the byte after the UID in block 0. if the above 2-way update were implemented, then an automatic calculation of BCC for a given UID would be super handy. but otherwise not needed.

**Comment by GameTec-live** [comment]
Yeah, no, not really gonna happen... theres a difference between the data on flash and the data the card reports, both on the CU as well as on real cards. It is the default behaviour, as thats how real cards do it too... For editing data without exporting and reimporting, the hexeditor is being worked on...
